# Generated by Django 5.1.4 on 2025-02-20 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên ứng viên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('new', 'Ứng viên Mới'), ('interviewed', 'Đã Phỏng vấn')], default='new', max_length=50, verbose_name='Trạng thái')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày ứng tuyển')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã thực tập sinh')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(max_length=20, verbose_name='Giới tính')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('education', models.CharField(max_length=100, verbose_name='Trình độ học vấn')),
                ('workExperience', models.TextField(blank=True, verbose_name='Kinh nghiệm làm việc')),
                ('documents', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('feedback_type', models.CharField(choices=[('positive', 'Tích cực'), ('negative', 'Tiêu cực'), ('neutral', 'Trung lập')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên phòng ban')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('location', models.CharField(max_length=200, verbose_name='Địa điểm')),
                ('participants', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Người tham gia')),
            ],
            options={
                'verbose_name': 'Sự kiện',
                'verbose_name_plural': 'Sự kiện',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('hrm', 'HRM'), ('lms', 'LMS')], max_length=50, verbose_name='Hệ thống')),
                ('integrated_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tích hợp')),
                ('integrated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tích hợp')),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Họ và tên')),
                ('email', models.EmailField(db_index=True, help_text='Nhập địa chỉ email hợp lệ', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(db_index=True, help_text='Nhập số điện thoại theo định dạng quốc tế, ví dụ: +84123456789', max_length=15, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải có định dạng hợp lệ.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('university', models.CharField(max_length=200, verbose_name='Trường đại học')),
                ('major', models.CharField(max_length=200, verbose_name='Chuyên ngành')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu thực tập')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc thực tập')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='interns/avatars/%Y/%m/', verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('active', 'Đang thực tập'), ('completed', 'Đã hoàn thành'), ('terminated', 'Đã chấm dứt')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to='home.department', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(auto_now_add=True, verbose_name='Ngày phản hồi')),
                ('content', models.TextField(verbose_name='Nội dung phản hồi')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Phản hồi từ quản lý')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Đã giải quyết')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='home.intern', verbose_name='Thực tập sinh')),
            ],
            options={
                'verbose_name': 'Phản hồi',
                'verbose_name_plural': 'Phản hồi',
                'ordering': ['-feedback_date'],
            },
        ),
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.candidate')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(verbose_name='Ngày phỏng vấn')),
                ('interview_time', models.TimeField(verbose_name='Thời gian phỏng vấn')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.candidate', verbose_name='Ứng viên')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phỏng vấn')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('platform', models.CharField(choices=[('website', 'Trang web Công ty'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed')], max_length=50, verbose_name='Nền tảng')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('notification_type', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('error', 'Lỗi'), ('success', 'Thành công')], default='info', max_length=20, verbose_name='Loại thông báo')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Liên kết')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên dự án')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('planned', 'Đã lên kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='planned', max_length=20, verbose_name='Trạng thái')),
                ('interns', models.ManyToManyField(related_name='projects', to='home.intern', verbose_name='Thực tập sinh')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý dự án')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Vị trí tuyển dụng')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(verbose_name='Yêu cầu')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mức lương')),
                ('posted_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày đăng')),
                ('deadline', models.DateField(verbose_name='Hạn nộp hồ sơ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
            options={
                'verbose_name': 'Tuyển dụng',
                'verbose_name_plural': 'Tuyển dụng',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nộp')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đánh giá')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='Nhận xét')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='medium', max_length=20, verbose_name='Mức độ ưu tiên')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn chót')),
                ('estimated_hours', models.PositiveIntegerField(default=0, verbose_name='Giờ ước tính')),
                ('actual_hours', models.PositiveIntegerField(default=0, verbose_name='Giờ thực tế')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người được giao')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Công việc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên chương trình')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm')),
                ('trainer', models.CharField(max_length=200, verbose_name='Người đào tạo')),
                ('max_participants', models.PositiveIntegerField(default=0, verbose_name='Số lượng tối đa')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái')),
                ('interns', models.ManyToManyField(related_name='training_programs', to='home.intern', verbose_name='Thực tập sinh')),
            ],
            options={
                'verbose_name': 'Chương trình đào tạo',
                'verbose_name_plural': 'Chương trình đào tạo',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hr', 'HR Manager'), ('coordinator', 'Internship Coordinator'), ('mentor', 'Mentor')], max_length=50, verbose_name='Vai trò')),
                ('permission', models.CharField(choices=[('read', 'Chỉ Đọc'), ('write', 'Đọc và Ghi')], max_length=50, verbose_name='Quyền Truy cập')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('score', models.PositiveIntegerField(verbose_name='Điểm số')),
                ('comments', models.TextField(verbose_name='Nhận xét')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.candidate', verbose_name='Ứng viên')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'unique_together': {('candidate', 'evaluator')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày điểm danh')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng mặt'), ('late', 'Đến muộn')], default='present', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='home.intern', verbose_name='Thực tập sinh')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'ordering': ['-date'],
                'unique_together': {('intern', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('evaluation_period', models.CharField(max_length=100, verbose_name='Kỳ đánh giá')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm số')),
                ('comments', models.TextField(verbose_name='Nhận xét')),
                ('is_final_evaluation', models.BooleanField(default=False, verbose_name='Đánh giá cuối kỳ')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Rất kém'), (2, 'Kém'), (3, 'Trung bình'), (4, 'Tốt'), (5, 'Xuất sắc')], default=3, verbose_name='Đánh giá')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='home.intern', verbose_name='Thực tập sinh')),
            ],
            options={
                'verbose_name': 'Đánh giá hiệu suất',
                'verbose_name_plural': 'Đánh giá hiệu suất',
                'ordering': ['-evaluation_date'],
                'unique_together': {('intern', 'evaluator', 'evaluation_period')},
            },
        ),
    ]
