# Generated by Django 5.1.4 on 2025-02-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_jobpost_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_active',
        ),
    ]
