# Generated by Django 5.1.4 on 2025-02-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
