# Generated by Django 5.1.4 on 2025-02-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
