# Generated by Django 5.1.4 on 2025-02-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_jobpost_is_active_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='location',
            field=models.CharField(default='Địa điểm chưa xác định', help_text='Địa điểm làm việc', max_length=200, verbose_name='Địa điểm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='salary_range',
            field=models.CharField(choices=[('Thỏa thuận', 'Thỏa thuận'), ('10-15 triệu', '10-15 triệu'), ('15-20 triệu', '15-20 triệu'), ('20+ triệu', '20+ triệu')], default='Thỏa thuận', max_length=100, verbose_name='Mức lương'),
        ),
    ]
