# Generated by Django 5.1.4 on 2025-02-15 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_recruitment_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-applied_date']},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='communication',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='intern',
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mức lương'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateevaluation',
            unique_together={('candidate', 'evaluator')},
        ),
    ]
