# Generated by Django 5.1.4 on 2025-02-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_candidate_options_alter_communication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_final',
        ),
    ]
