# Generated by Django 5.1.4 on 2025-02-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_profile_alter_communication_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='trainee_id',
            new_name='id',
        ),
    ]
