# Generated by Django 5.1.4 on 2025-02-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_report_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='intern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.intern', verbose_name='Thực tập sinh'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_final',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Báo cáo cuối kỳ'),
        ),
    ]
