# Generated by Django 5.1.4 on 2025-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_work_experience_profile_workexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='trainer',
            field=models.CharField(max_length=200, verbose_name='Người đào tạo'),
        ),
    ]
