# Generated by Django 5.1.4 on 2025-02-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_report_intern_report_is_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='intern',
        ),
        migrations.AddField(
            model_name='report',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.candidate', verbose_name='Ứng viên'),
        ),
    ]
