# Generated by Django 5.1.4 on 2025-02-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_report_intern_report_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='candidate',
        ),
        migrations.AddField(
            model_name='report',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='home.recruitment', verbose_name='Chiến dịch Tuyển dụng'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('recruitment_list', 'Danh sách Chiến dịch Tuyển dụng'), ('weekly', 'Báo cáo tuần'), ('monthly', 'Báo cáo tháng'), ('final', 'Báo cáo cuối kỳ')], default='weekly', max_length=50, verbose_name='Loại báo cáo'),
        ),
    ]
