# Generated by Django 5.1.4 on 2025-02-16 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_report_candidate_report_recruitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='review_date',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Ngày tạo'),
        ),
    ]
