# Generated by Django 5.1.4 on 2025-02-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_report_review_date_report_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='recruitment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='report',
            name='intern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.intern', verbose_name='Thực tập sinh'),
        ),
        migrations.AddField(
            model_name='report',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đánh giá'),
        ),
    ]
