# Generated by Django 5.1.4 on 2025-02-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_report_created_at_remove_report_recruitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_final',
        ),
        migrations.AlterField(
            model_name='report',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.intern', verbose_name='Thực tập sinh'),
        ),
    ]
