# Generated by Django 5.1.4 on 2025-02-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_report_is_final_alter_report_intern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='intern',
        ),
    ]
